### ISSUE TITLE
Display Pending to-do list number

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#302]
![Screenshot (6)](https://user-images.githubusercontent.com/28754174/81295391-f5fcdf00-908d-11ea-9774-e442f757285e.png)

**Comment by moumitahalder** [comment]
Getting this error :
```
Notice: Undefined variable: WCMp in /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-fix-302/includes/wcmp-core-functions.php on line 1857

Notice: Trying to get property 'product_qna' of non-object in /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-fix-302/includes/wcmp-core-functions.php on line 1857

Fatal error: Uncaught Error: Call to a member function get_Pending_Questions() on null in /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-fix-302/includes/wcmp-core-functions.php:1857 Stack trace: #0 /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-fix-302/classes/class-wcmp-admin.php(310): wcmp_count_to_do_list() #1 /home/wcmpdemos/public_html/moumita/wp-includes/class-wp-hook.php(287): WCMp_Admin->wcmp_submenu_count('') #2 /home/wcmpdemos/public_html/moumita/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #3 /home/wcmpdemos/public_html/moumita/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #4 /home/wcmpdemos/public_html/moumita/wp-admin/admin-header.php(149): do_action('admin_head') #5 /home/wcmpdemos/public_html/moumita/wp-admin/plugins.php(486): require_once('/home/wcmpdemos...') #6 {main} thrown in /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-fix-302/includes/wcmp-core-functions.php on line 1857
```
