### ISSUE TITLE
Error at the time of withdrawal 

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#310]
Fatal error: Uncaught Error: Call to a member function get_order() on boolean in /home/www/fv.bfyn.ca/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-wcmp-post-transaction.php:221 Stack trace: #0 /home/www/fv.bfyn.ca/wp-content/plugins/dc-woocommerce-multi-vendor/templates/emails/vendor-commissions-transaction.php(28): WCMp_Transaction->get_transaction_item_details(203) #1 /home/www/fv.bfyn.ca/wp-content/plugins/woocommerce/includes/wc-core-functions.php(251): include(‘/home/www/fv.bf…’) #2 /home/www/fv.bfyn.ca/wp-content/plugins/dc-woocommerce-multi-vendor/classes/emails/class-wcmp-email-vendor-new-commission-transaction.php(104): wc_get_template(’emails/vendor-c…’, Array, ‘dc-product-vend…’, ‘/home/www/fv.bf…’) #3 /home/www/fv.bfyn.ca/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(540): WC_Email_Vendor_Commission_Transactions->get_content_html() #4 /home/www/fv.bfyn.ca/wp-content/plugins/dc-woocommerce-multi-vendor/classes/emails/class-wcmp-email-vendor-new-commission-transaction. in /home/www/fv.bfyn.ca/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-wcmp-post-transaction.php on line 221

**Comment by moumitahalder** [comment]
Another error :

Warning: A non-numeric value encountered in /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-master/classes/class-wcmp-post-transaction.php on line 324

Warning: Cannot modify header information - headers already sent by (output started at /home/wcmpdemos/public_html/moumita/wp-content/plugins/dc-woocommerce-multi-vendor-master/classes/class-wcmp-post-transaction.php:320) in /home/wcmpdemos/public_html/moumita/wp-includes/pluggable.php on line 1281
