### ISSUE TITLE
Parameter Mismatch 

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/dc-woocommerce-multi-vendor#919]
Uncaught ArgumentCountError: Too few arguments to function
GoDaddy\WordPress\MWC\Core\WooCommerce\ShipmentsTable::maybeRenderEmailShipmentsTable(),
2 passed in /var/www/wp-includes/class-wp-hook.php on line 303 and exactly 4
expected in /var/www/wp-content/mu-plugins/gd-system-plugin/plugins/mwc-core/src/WooCommerce/ShipmentsTable.php:79
Stack trace: #0 /var/www/wp-includes/class-wp-hook.php(303): GoDaddy\WordPress\MWC\Core\WooCommerce\ShipmentsTable->
maybeRenderEmailShipmentsTable(Object(WC_Order), true)
#1 /var/www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(”, Array)
#2 /var/www/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#3 /var/www/wp-content/plugins/dc-woocommerce-multi-vendor/templates/emails/vendor-notify-shipped.php(55): do_action(‘woocommerce_ema…’, Object(WC_Order), true)
#4 /var/www/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include(‘/var/www/wp-con…’)
#5 /var/www/wp-content/plugins/dc-woocommerce-multi-vendor/classes/emails/class-wcmp-email- in /var/www/wp-content/mu-plugins/gd-system-plugin/plugins/mwc-core/src/WooCommerce/ShipmentsTable.php on line 79

**Comment by moumitahalder** [comment]
src https://wc-marketplace.com/support-forum/topic/error-on-wcmp-vendor-new-order/#post-125427
